Milestone-5 of  Bookstore-CMS Project
Samitti/Bookstore-CMS-Redux pull request #5
Opened 2021-01-25 18:56 UTC by Samitti

Hi, I have changed the design to the specification given and styled it. 
Kindly review my code, thanks.

2021-01-25 19:24 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @Samitti 👋 
Good job, you have done implementing the design of this project. Keep it up 👍 
We are almost done, just a few changes to work on before we proceed, 👇 
### Happy coding 💻 
#### Christian Otieno (CR)

2021-01-25 19:24 UTC, christianotieno commented on src/components/App.css
> +
## Improve the Design 
- [ ] Improve the page layout to match that of the design given. Currently, what we have is a page\s content leaning on the left side of the site and is not as responsive as expected. The styling should be **EXACTLY** the same as the one provided in the designs ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/exactlySameAsDesign.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/))

|Required Design|Current Implemetation|
|:---:|:---:|
|![bookstore-design](https://user-images.githubusercontent.com/22345961/105754712-7389b780-5f5b-11eb-83d7-8d910a2ef3d0.png)|![bookstore-implementation](https://user-images.githubusercontent.com/22345961/105754745-7be1f280-5f5b-11eb-9f80-5a3180f0a89b.png)|

2021-01-26 09:05 UTC, Samitti commented
Hi, I have added media-query to reflect the same design as required, kindly review my code.

2021-01-26 09:52 UTC, Samitti commented
Hi, I have added media-query to reflect the same design as required, kindly review my code.

2021-01-26 10:49 UTC, uche-inyama requested changes
## Changes Required

Hi @Samitti :wave: 

I can see you have centered the content of the page, like my colleague asked. However, if you observe, you will notice that the **book component** is not centered properly, it stretches all the way to the right; there should be a margin on the right of each book card.

I have left a comment below, suggesting how you could resolve it.

That's it, make the change, then submit another form for a code review

#### If you need clarifications reach out on slack. @ Inyama, Uchechukwu Henry

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

2021-01-26 10:49 UTC, uche-inyama commented on src/components/App.css
> +
I would suggest you make your width: 90%; margin: 20px auto, to center it.

2021-01-26 14:44 UTC, Samitti commented
Hi, I have made the changes requested. Kindly review my code.

2021-01-26 14:49 UTC, Samitti commented
Hi, I am sorry to say this but my milestone-2 is not reviewed until now, can you suggest to me also what to do to that milestone...

2021-01-26 16:51 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @Samitti, great job on this project :+1: You did a great job fixing the comments outline by the previous TSE's :smile: Awesome, however, the app is not responsive as expected on large devices. Kindly check the screenshots to understand the problem

- The first has to do with the user profile not showing completely and the other one has to do with the horizontal scroll
![pr](https://user-images.githubusercontent.com/46388113/105875787-20b10e00-5ff6-11eb-8c4f-40dfb4c88d3d.png)
![hr](https://user-images.githubusercontent.com/46388113/105875809-29a1df80-5ff6-11eb-9571-132eae7d182d.png)

[Optional]
- Currently, our app is not mobile-friendly, it would be nice if we implement mobile responsive for it

Kindly fix this and submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-01-27 07:49 UTC, Samitti commented
Hi, I have made all the changes required, kindly review my code.

2021-01-27 08:47 UTC, trekab approved these changes
### Approved! :tada: 
Well done working on the suggested changes @Samitti! You may proceed to the final milestone. Please update your deployed version as well.

__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2021-01-27 13:40 UTC, merged